export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const SELECTED_COUNTRY = 'SELECTED_COUNTRY';
export const POST_COUNTRY_DATA = 'POST_COUNTRY_DATA';
export const SET_OPT_IN_TYPE = 'SET_OPT_IN_TYPE';
